In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('OK2018Apr_tranV2.csv')

In [3]:
df.shape

(1048575, 15)

In [4]:
df.head()

,Store ID,Store Type,Trans ID,Date,Time,Member ID,Member Grade,Gender,Member Birthday,Dept,Cat,Subcat,Sold Qty,MOP,Amount
0,27,HSR - HIGH STREET RESIDENTIAL,8151518418,1/4/2018,6:06:47,NaN,NaN,NaN,NaN,Publications,Newspaper,Newspaper (General),1,Cash,8.0
1,27,HSR - HIGH STREET RESIDENTIAL,8151518418,1/4/2018,6:06:48,NaN,NaN,NaN,NaN,Publications,Misc,Misc (General),1,Cash,0.0
2,27,HSR - HIGH STREET RESIDENTIAL,8151518418,1/4/2018,6:06:49,NaN,NaN,NaN,NaN,Publications,Promotion Coupon,Promotion Coupon (General),1,Cash,-0.5
3,27,HSR - HIGH STREET RESIDENTIAL,8151518417,1/4/2018,6:07:29,NaN,NaN,NaN,NaN,Publications,Newspaper,Newspaper (General),1,Cash,8.0
4,27,HSR - HIGH STREET RESIDENTIAL,8151518417,1/4/2018,6:07:30,NaN,NaN,NaN,NaN,Publications,Misc,Misc (General),1,Cash,0.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 15 columns):
Store ID           1048575 non-null int64
Store Type         1048575 non-null object
Trans ID           1048575 non-null int64
Date               1048575 non-null object
Time               1048575 non-null object
Member ID          196515 non-null float64
Member Grade       196502 non-null object
Gender             189076 non-null object
Member Birthday    171704 non-null object
Dept               975135 non-null object
Cat                975135 non-null object
Subcat             974952 non-null object
Sold Qty           1048575 non-null int64
MOP                1048575 non-null object
Amount             1048575 non-null float64
dtypes: float64(2), int64(3), object(10)
memory usage: 120.0+ MB

In [6]:
df['Store ID'].value_counts(dropna=False)

279      156144
27       129003
81180    122327
81283    114362
81982    114007
811      104659
630       81031
92        80724
81781     74306
81688     72012
Name: Store ID, dtype: int64

In [7]:
df['Store Type'].value_counts(dropna=False)

HPU - PUBLIC HOUSING             766529
HSR - HIGH STREET RESIDENTIAL    201015
HPR - PRIVATE HOUSING             81031
Name: Store Type, dtype: int64

In [8]:
df['Trans ID'].value_counts(dropna=False)

7279723868    61
8180790490    57
7224491683    55
8124978214    55
7236357926    54
8132800495    53
8165974352    50
7246903967    48
7224530899    46
7235401182    45
7235378713    43
8147044055    43
7279705949    42
7236306133    41
7249331985    38
7235619108    38
7224527223    37
8124887226    37
7224498413    35
7224325144    35
7224328819    34
7224620898    34
7224491889    34
8143633966    34
8132822973    34
8147092170    33
7224273566    33
8147073562    33
7235397426    33
7254955548    32
              ..
7246888310     1
7246894459     1
8132947324     1
8133006532     1
7247037825     1
7236558210     1
8165963668     1
7224911181     1
7236437321     1
8169532676     1
7224544555     1
8181073161     1
7224775947     1
8137781581     1
7236322577     1
7224796437     1
8181105945     1
7236343067     1
7279634751     1
8181009704     1
7249272175     1
7200035945     1
7236252975     1
7279728719     1
8181030194     1
8148059408     1
7236273465     1
7224747325     1
7224890691     1
8180994050     1
Name: Trans ID, Length: 527016, dtype: int64

In [9]:
df[df['Trans ID']==7279723868]

,Store ID,Store Type,Trans ID,Date,Time,Member ID,Member Grade,Gender,Member Birthday,Dept,Cat,Subcat,Sold Qty,MOP,Amount
886927,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:38:47,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chips,Potato,1,Octopus,11.9
886929,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:38:49,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chips,Potato,1,Octopus,11.9
886932,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:38:53,27397820.0,G,F,6/9/2003,Confectionery & Snack,Other Snacks,Internation Value Japan,1,Octopus,18.9
886933,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:38:55,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chocolate,Internation Value Japan,1,Octopus,16.9
886934,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:38:58,27397820.0,G,F,6/9/2003,Beer & Mixed Drinks,KING CAN,CARLSBERG,1,Octopus,11.5
886935,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:38:58,27397820.0,G,F,6/9/2003,Beer & Mixed Drinks,KING CAN,CARLSBERG,1,Octopus,11.5
886936,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:38:58,27397820.0,G,F,6/9/2003,Beer & Mixed Drinks,KING CAN,CARLSBERG,1,Octopus,11.5
886937,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:38:59,27397820.0,G,F,6/9/2003,Beer & Mixed Drinks,KING CAN,CARLSBERG,1,Octopus,11.5
886938,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:08,27397820.0,G,F,6/9/2003,Grocery,Packaged Bakery,International Value Japan,1,Octopus,18.5
886939,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:12,27397820.0,G,F,6/9/2003,Confectionery & Snack,Other Snacks,Internation Sourcing Japan,1,Octopus,10.9
886940,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:15,27397820.0,G,F,6/9/2003,Dairy,Soya Milk,236ML,1,Octopus,6.1
886941,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:17,27397820.0,G,F,6/9/2003,Dairy,Soya Milk,236ML,1,Octopus,6.1
886942,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:19,27397820.0,G,F,6/9/2003,Dairy,Soya Milk,236ML,1,Octopus,6.1
886943,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:22,27397820.0,G,F,6/9/2003,Dairy,Soya Milk,236ML,1,Octopus,6.1
886944,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:24,27397820.0,G,F,6/9/2003,Packaged Beverage,Juice Drinks,Bottle,1,Octopus,9.5
886945,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:26,27397820.0,G,F,6/9/2003,Packaged Beverage,Juice Drinks,Bottle,1,Octopus,9.5
886946,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:29,27397820.0,G,F,6/9/2003,Packaged Beverage,Juice Drinks,Bottle,1,Octopus,9.5
886947,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:30,27397820.0,G,F,6/9/2003,Packaged Beverage,Juice Drinks,Bottle,1,Octopus,9.5
886948,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:34,27397820.0,G,F,6/9/2003,Packaged Beverage,Flavoured Water,SM<=500ML,1,Octopus,8.5
886949,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:36,27397820.0,G,F,6/9/2003,Packaged Beverage,Flavoured Water,SM<=500ML,1,Octopus,8.5
886950,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:39,27397820.0,G,F,6/9/2003,Packaged Beverage,Flavoured Water,SM<=500ML,1,Octopus,8.5
886952,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:42,27397820.0,G,F,6/9/2003,Packaged Beverage,Flavoured Water,SM<=500ML,1,Octopus,8.5
886953,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:49,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chocolate,Bite Size,1,Octopus,16.9
886954,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:49,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chocolate,Bite Size,1,Octopus,16.9
886955,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:50,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chocolate,Bite Size,1,Octopus,16.9
886956,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:50,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chocolate,Bite Size,1,Octopus,16.9
886957,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:54,27397820.0,G,F,6/9/2003,Confectionery & Snack,Candy,Chewy,1,Octopus,7.5
886958,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:55,27397820.0,G,F,6/9/2003,Confectionery & Snack,Candy,Chewy,1,Octopus,7.5
886959,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:58,27397820.0,G,F,6/9/2003,Confectionery & Snack,Candy,Chewy,1,Octopus,7.5
886960,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:39:58,27397820.0,G,F,6/9/2003,Confectionery & Snack,Candy,Chewy,1,Octopus,7.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886962,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:01,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chocolate,Japan Chocolate,1,Octopus,15.9
886963,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:04,27397820.0,G,F,6/9/2003,Confectionery & Snack,Other Snacks,Internation Sourcing Japan,1,Octopus,21.9
886964,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:15,27397820.0,G,F,6/9/2003,A & P Expense,Promotion Coupon,JAPANESE VALUE ZONE COUPON,1,Octopus,-25.0
886965,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chocolate,Bite Size,1,Octopus,-7.0
886966,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chocolate,Bite Size,1,Octopus,-7.0
886967,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chocolate,Bite Size,1,Octopus,-7.0
886968,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chocolate,Bite Size,1,Octopus,-7.0
886969,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chips,Potato,1,Octopus,-6.9
886970,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Confectionery & Snack,Chips,Potato,1,Octopus,-6.9
886971,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Confectionery & Snack,Candy,Chewy,1,Octopus,-3.0
886972,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Confectionery & Snack,Candy,Chewy,1,Octopus,-3.0
886973,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Confectionery & Snack,Candy,Chewy,1,Octopus,-3.0
886974,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Confectionery & Snack,Candy,Chewy,1,Octopus,-3.0
886975,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:16,27397820.0,G,F,6/9/2003,Dairy,Soya Milk,236ML,1,Octopus,-2.6
886976,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:17,27397820.0,G,F,6/9/2003,Dairy,Soya Milk,236ML,1,Octopus,-2.6
886977,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:17,27397820.0,G,F,6/9/2003,Dairy,Soya Milk,236ML,1,Octopus,-2.6
886978,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:17,27397820.0,G,F,6/9/2003,Dairy,Soya Milk,236ML,1,Octopus,-2.6
886979,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:17,27397820.0,G,F,6/9/2003,Packaged Beverage,Flavoured Water,SM<=500ML,1,Octopus,-3.5
886980,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:17,27397820.0,G,F,6/9/2003,Packaged Beverage,Flavoured Water,SM<=500ML,1,Octopus,-3.5
886981,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:18,27397820.0,G,F,6/9/2003,Packaged Beverage,Flavoured Water,SM<=500ML,1,Octopus,-3.5
886982,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:18,27397820.0,G,F,6/9/2003,Packaged Beverage,Flavoured Water,SM<=500ML,1,Octopus,-3.5
886983,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:18,27397820.0,G,F,6/9/2003,Packaged Beverage,Juice Drinks,Bottle,1,Octopus,-4.0
886984,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:18,27397820.0,G,F,6/9/2003,Packaged Beverage,Juice Drinks,Bottle,1,Octopus,-4.0
886985,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:18,27397820.0,G,F,6/9/2003,Packaged Beverage,Juice Drinks,Bottle,1,Octopus,-4.0
886986,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:18,27397820.0,G,F,6/9/2003,Packaged Beverage,Juice Drinks,Bottle,1,Octopus,-4.0
886987,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:18,27397820.0,G,F,6/9/2003,Beer & Mixed Drinks,KING CAN,CARLSBERG,1,Octopus,-4.5
886988,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:18,27397820.0,G,F,6/9/2003,Beer & Mixed Drinks,KING CAN,CARLSBERG,1,Octopus,-4.5
886989,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:18,27397820.0,G,F,6/9/2003,Beer & Mixed Drinks,KING CAN,CARLSBERG,1,Octopus,-4.5
886990,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:19,27397820.0,G,F,6/9/2003,Beer & Mixed Drinks,KING CAN,CARLSBERG,1,Octopus,-4.5
886991,81283,HPU - PUBLIC HOUSING,7279723868,21/4/2018,17:40:19,27397820.0,G,F,6/9/2003,A & P Expense,LOYALTYPROG COU,LOYALTYPROG COU(General),1,Octopus,-5.0

In [10]:
print(df['Date'].nunique())
df['Date'].value_counts(dropna=False)

31

21/4/2018    41344
25/4/2018    40814
20/4/2018    38757
22/4/2018    38041
23/4/2018    38010
19/4/2018    37899
14/4/2018    37676
24/4/2018    37626
13/4/2018    36607
15/4/2018    35873
8/4/2018     35858
18/4/2018    35657
11/4/2018    35423
12/4/2018    35255
10/4/2018    34666
17/4/2018    34513
9/4/2018     34183
29/4/2018    33970
2/4/2018     33339
6/4/2018     33165
16/4/2018    32893
5/4/2018     32860
28/4/2018    32439
7/4/2018     32414
3/4/2018     32003
4/4/2018     31850
27/4/2018    31522
30/4/2018    31221
1/4/2018     29976
26/4/2018    29824
1/5/2018      2897
Name: Date, dtype: int64

In [11]:
print(df['Time'].nunique())
df['Time'].value_counts(dropna=False)

84029

7:35:17    51
7:49:01    51
7:39:40    49
7:44:22    47
8:39:20    47
8:08:12    46
7:57:56    46
7:38:59    46
7:41:47    46
8:34:12    46
8:01:52    45
7:52:15    45
7:02:06    45
7:22:05    45
7:55:59    45
7:33:23    45
7:43:05    45
7:58:25    44
8:02:44    44
7:21:17    44
7:53:54    44
7:20:36    44
8:35:28    44
7:42:07    44
7:41:45    44
7:48:29    44
7:49:46    44
8:31:01    44
7:50:31    44
7:27:07    44
           ..
3:14:51     1
5:08:16     1
1:21:04     1
4:54:09     1
4:20:27     1
2:36:52     1
1:59:59     1
3:12:41     1
2:49:49     1
4:48:09     1
3:56:00     1
1:42:30     1
5:37:38     1
2:58:22     1
3:21:09     1
1:39:04     1
2:38:13     1
4:26:34     1
2:38:21     1
1:55:35     1
1:51:45     1
4:36:14     1
2:18:27     1
4:57:26     1
4:22:13     1
5:01:45     1
4:45:07     1
3:38:36     1
3:02:48     1
4:12:04     1
Name: Time, Length: 84029, dtype: int64

In [12]:
print(df['Member ID'].nunique())
df['Member ID'].value_counts(dropna=False)

22066

NaN             852060
 27913460.0        361
 63609607.0        315
 81633566.0        247
 45838610.0        246
 81623060.0        222
 18991881.0        211
 637027.0          211
 815543.0          210
 9049703.0         209
 2756936.0         195
 724154.0          192
 18378718.0        191
 63632079.0        190
 63238116.0        190
 811582.0          187
 8106136.0         187
 45573564.0        187
 5429204.0         183
 45508413.0        181
 18127626.0        181
 6354559.0         176
 815446.0          176
 9782172.0         174
 725547.0          174
 6379003.0         173
 81804152.0        168
 817221.0          164
 27096136.0        160
 81379804.0        159
                 ...
 27438311.0          1
 9785248.0           1
 54652370.0          1
 9785648.0           1
 54650196.0          1
 54649404.0          1
 72991884.0          1
 819556839.0         1
 54658414.0          1
 54659501.0          1
 9778518.0           1
 72662576.0          1
 27429402.0          1
 54671289.0          1
 9768213.0           1
 9769208.0           1
 27430195.0          1
 72662378.0          1
 27432475.0          1
 9770992.0           1
 9772474.0           1
 1841787.0           1
 54663668.0          1
 9773367.0           1
 18935444.0          1
 9774859.0           1
 27432579.0          1
 27433161.0          1
 72989201.0          1
 7220993.0           1
Name: Member ID, Length: 22067, dtype: int64

In [13]:
print(df['Member Birthday'].nunique())
df['Member Birthday'].value_counts(dropna=False)

493

NaN           876871
26/9/2002       2841
21/2/2003       1004
6/4/2003         977
10/9/2003        951
4/5/2003         898
5/9/2003         876
6/7/2003         873
26/12/2002       867
29/10/2002       863
4/2/2003         849
14/11/2002       799
28/10/2002       799
7/10/2002        793
28/6/2003        777
27/2/2003        759
26/9/2003        748
22/7/2003        743
11/6/2003        733
6/1/2003         732
6/8/2003         719
8/9/2003         717
8/6/2003         716
12/8/2003        715
8/7/2003         713
15/5/2003        712
16/6/2003        710
27/4/2003        706
4/3/2003         703
28/5/2003        695
               ...
5/2/1993           3
11/5/1993          3
21/12/1992         3
23/3/1993          2
16/5/1993          2
29/3/1993          2
26/2/1993          2
11/11/1992         2
22/10/1992         2
2/8/1993           2
3/5/1993           2
13/9/1993          2
16/4/1993          2
5/9/1993           2
2/2/1993           1
7/9/1993           1
11/4/1993          1
16/3/1993          1
8/11/1992          1
2/12/1992          1
14/1/1993          1
25/9/1993          1
25/11/1992         1
19/9/1993          1
7/5/1993           1
24/5/1993          1
19/4/1993          1
2/5/1993           1
9/9/1993           1
22/5/1993          1
Name: Member Birthday, Length: 494, dtype: int64

In [14]:
print(df['Member Grade'].nunique())
df['Member Grade'].value_counts(dropna=False)

3

NaN    852073
G      112256
S       76820
O        7426
Name: Member Grade, dtype: int64

In [15]:
df['Gender'].value_counts(dropna=False)

NaN    859499
M       95667
F       93409
Name: Gender, dtype: int64

In [16]:
print(df['Dept'].nunique())
df['Dept'].value_counts(dropna=False)

20

Publications             222370
Convenience Services     168951
Packaged Beverage        149745
Tobacco                   79494
NaN                       73440
Confectionery & Snack     66122
Dairy                     56207
Beer & Mixed Drinks       50584
Packaged Ice Cream        48400
Food Service              35066
Grocery                   28657
A & P Expense             20635
Full-baked Ambient        14937
HOT & IN                  14598
Non-Food                  13284
Deposit                    3202
Wine & Spirit              1396
Instore Bakery              736
Catering Item               637
Store Use Items              71
Gift Tin                     43
Name: Dept, dtype: int64

In [17]:
print(df['Cat'].nunique())
df['Cat'].value_counts(dropna=False)

121

Octopus                           104128
Newspaper                         100116
Cigarette                          79068
NaN                                73440
Promotion Coupon                   61533
Misc                               53421
Tea                                48045
Packaged Bakery                    26954
KING CAN                           26427
SAINT HONORE                       23162
Novelty                            20680
Cone                               18688
Coffee                             17457
Energy Drinks                      17212
Carbonated Drinks                  17086
Soya Drink                         16429
Candy                              15944
Bill Payment                       15916
Chips                              15585
LOYALTYPROG COU                    13863
Fresh Milk                         13812
Other Snacks                       12389
Juice Drinks                       10841
Chocolate                          10543
FBA Bun                            10466
Hi Cal                             10323
Magazine                            9393
STEAM STATION                       9082
CAN                                 8992
Cup Noodle                          8749
                                   ...
Raining Accessories                  260
Yoghurt Drink                        241
Health & Beauty                      239
Condiment                            206
BOOKS                                200
Health Supplement                    189
OCTOPUS                              174
Hard Liquor                          152
MISC                                 133
Pastry                               130
PICK & DELIVER SERVICES              126
Family Pack                          106
Soup                                  89
Canned Food                           87
Special Cards                         54
Circle K Only                         40
Thematic Promotion                    27
Japanese Wine                         26
E CREDITS                             25
FUN & NOVELTY                         23
Vending                               18
LOCAL FAX & COPY                      18
Stationery                            13
Party Ware                            13
Toy Candy                             11
PRE-ORDER                              6
Cash Withdrawal                        3
Phone Cards                            3
Maps                                   2
iLike Payment                          2
Name: Cat, Length: 122, dtype: int64

In [18]:
print(df['Subcat'].nunique())
df['Subcat'].value_counts(dropna=False)

307

Octopus (General)                 104119
Newspaper (General)                96808
Bottle                             78499
NaN                                73623
Promotion Coupon (General)         60756
Misc (General)                     53240
236ML                              24190
Non-Menthol Full Flavor KS         23819
Tetra Pack                         21900
Nestle                             19834
Can                                16830
Non-Menthol Lights KS              15447
Menthol Ultra Lights KS            14773
ORIENTAL BUN                       14670
Menthol Lights KS                  14322
LOYALTYPROG COU(General)           13863
Appolo                             12694
375 T/P                            11612
FBA Bun(General)                   10466
Cakes                               9814
Potato                              9255
946ML                               8224
SKOL                                8194
SM<=500ML                           8173
500ML<MED<=800ML                    7775
HOT TITLES                          7416
CARLSBERG                           7048
Misc                                6945
PET SM 600ML<=                      6788
drink                               5986
                                   ...
FUNG SHUI & HOROSCOPE                 15
Chocolate (General)                   13
Party Ware (General)                  13
Stationery (General)                  13
Hair Styling                          12
PROMOTION(General)                    11
SPECIAL DRINKS                        11
Accessories                           11
Local Toy Candy                       11
Tissue                                10
ST.HONORE                              9
TRENDY GIFTS                           9
Hair Removal                           9
Miscellanous                           9
FICTION                                7
Deodorant                              6
VCD & DVD                              6
*                                      6
INTERNATIONAL JAPANESE                 5
GLOBAL SOURCING JAPAN                  5
US$50                                  3
EPS-Pure Cash Back                     3
Moisturizer                            3
YAMATO BILL PAYMENT                    3
iLike Payment(General)                 2
Maps (General)                         2
YAMATO                                 2
INTERNATION VALUEJAPAN                 1
AT SERVICES LIMITED                    1
Personal Wash                          1
Name: Subcat, Length: 308, dtype: int64

In [19]:
print(df['Sold Qty'].nunique())
df['Sold Qty'].value_counts(dropna=False)

63

 1      1021810
 2        14876
 3         3475
 4         2781
-1         2193
 6         1395
 5          544
 10         441
 8          310
 12         119
 9          116
 7          100
 24          49
 20          30
 15          29
-2           26
 50          23
 11          23
 31          21
 99          21
 16          19
 14          18
 30          18
 13          15
-4           11
 17           9
 25           9
 60           7
 18           7
-3            6
         ...
 42           5
 90           5
 23           3
-10           3
 240          3
-8            3
 19           3
 21           3
 62           2
-12           2
 22           2
-5            2
 29           2
 32           2
 70           2
-16           1
 35           1
-15           1
 93           1
 65           1
 83           1
 72           1
 71           1
 33           1
 48           1
 47           1
 27           1
 38           1
-7            1
 34           1
Name: Sold Qty, Length: 63, dtype: int64

In [20]:
print(df['MOP'].nunique())
df['MOP'].value_counts(dropna=False)

8

Cash                                586212
Octopus                             421789
Alipay                               12744
EPS                                  11542
VISA/MASTR                            9357
Wepay                                 6517
TNG                                    233
CUP_Unionpay                           181
Name: MOP, dtype: int64

In [21]:
print(df['Amount'].nunique())
print(df['Amount'].max())
df['Amount'].value_counts(dropna=False)

3889
5998.0

 8.0       114867
 57.0       59334
 0.0        58971
 100.0      54484
-1.0        51695
 7.5        32053
 8.5        30510
 50.0       20980
 10.0       20408
 200.0      19999
 9.0        18797
 9.5        18611
 11.5       18452
-2.0        18266
 11.0       18145
-0.5        13467
-5.0        12406
 7.0        11621
 10.5       11286
 500.0      10927
 6.0        10794
 7.2         9883
 10.9        9866
 9.9         9048
 11.9        8783
 13.0        8712
 13.5        8686
 8.9         8535
 16.9        8445
-3.0         8029
            ...
 1584.0         1
 200.4          1
 3797.0         1
 802.4          1
 951.0          1
 2032.0         1
 119.2          1
 362.6          1
 98.3           1
 165.5          1
 1808.0         1
 3814.0         1
 3815.0         1
 744.2          1
 3428.0         1
 1014.0         1
 24.7           1
 394.8          1
 744.3          1
 902.0          1
 394.2          1
 959.0          1
 186.7          1
 2985.7         1
 59.7           1
 90.9           1
 155.6          1
 268.8          1
 90.1           1
 127.2          1
Name: Amount, Length: 3889, dtype: int64

In [22]:
df = pd.read_csv('OK2018Apr_tranV2.csv')